/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Edit versions/V5.5/meta.json for label/note (and optionally this
 * version's own title-header hero video — heroPlaylistId/heroVideoIds/
 * heroVideoId, same shape as project-data.js's site-level hero), add/remove
 * files in versions/V5.5/assets/ for images and local videos, drop at most
 * one PDF in versions/V5.5/assets/ for the drawing-set viewer + download
 * button, or add entries to versions/V5.5/videos.json for non-file videos
 * (e.g. YouTube) — then re-run: node scripts/generate-version-data.js
 */
window.VERSIONS = window.VERSIONS || {};
window.VERSIONS["V5.5"] = {
  id: "V5.5",
  label: "V5.5",
  note: "BUILT IN BAJA BENCH WITH SITTING AREA,FULLY COVERED FIREPIT AREA WITH PROJECTOR SCREEN, ROOF DECK AREA OVER FIREPIT",
  thumb: "assets/01-1.jpg",
  // Title-header hero video — checked in this order, first non-empty wins,
  // falls back to the thumb image (above) as a static background if all
  // three are empty. See assets/js/common.js buildYouTubeHeroSrc().
  heroPlaylistId: "PLFgzgcOzYDN0",
  heroVideoIds: [],
  heroVideoId: "",
  // Drawing-set PDF found in assets/ (null if none) — powers the PDF viewer
  // + download button on this version's subpage. See version-page.js.
  pdf: { src: "assets/CLEARVIEW-DECK-DV5.5-1-PATIO-DECK.pdf", label: "Drawing Set (PDF)" },
  images: [
    { src: "assets/01-1.jpg", caption: "01 1" },
    { src: "assets/01-2.jpg", caption: "01 2" },
    { src: "assets/02-aerial-deck-and-pool-view.jpg", caption: "02 Aerial Deck And Pool View" },
    { src: "assets/03-aerial-deck-and-pool-dusk.jpg", caption: "03 Aerial Deck And Pool Dusk" },
    { src: "assets/04-pergola-pool-terrace-view.jpg", caption: "04 Pergola Pool Terrace View" },
    { src: "assets/06-terrace-steps-to-pool.jpg", caption: "06 Terrace Steps To Pool" },
    { src: "assets/07-pergola-shade-detail.jpg", caption: "07 Pergola Shade Detail" },
    { src: "assets/08-deck-walkway-dusk-view.jpg", caption: "08 Deck Walkway Dusk View" },
    { src: "assets/09-pool-corridor-view.jpg", caption: "09 Pool Corridor View" },
    { src: "assets/10-dining-terrace-interior-view.jpg", caption: "10 Dining Terrace Interior View" },
    { src: "assets/11-bbq-kitchen-detail.jpg", caption: "11 Bbq Kitchen Detail" },
    { src: "assets/12-evening-terrace-view.jpg", caption: "12 Evening Terrace View" },
    { src: "assets/13-outdoor-movie-night-fire-pit.jpg", caption: "13 Outdoor Movie Night Fire Pit" },
    { src: "assets/14-outdoor-movie-night-screen-view.jpg", caption: "14 Outdoor Movie Night Screen View" },
    { src: "assets/16-outdoor-movie-night-twilight.jpg", caption: "16 Outdoor Movie Night Twilight" },
    { src: "assets/z-aerial-site-overview.jpg", caption: "Z Aerial Site Overview" }
  ],
  videos: [
    { type: "youtube", youtubeId: "as7UumMWGa0", caption: "Fire Pit" },
    { type: "youtube", youtubeId: "B7Y6PoER8PU", caption: "Sun Study" },
    { type: "youtube", youtubeId: "GIv6Fzz-06o", caption: "Projection Screen" },
    { type: "youtube", youtubeId: "J14n4W3_BQ4", caption: "Flythrough 1" },
    { type: "youtube", youtubeId: "xPEuINdMmh8", caption: "Flythrough 2" },
    { type: "youtube", youtubeId: "SzfP0PZthf8", caption: "Projection Screen 2" }
  ]
};
