/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Edit versions/v5-4/meta.json for label/note, add/remove files in
 * versions/v5-4/assets/ for images and local videos, or add entries to
 * versions/v5-4/videos.json for non-file videos (e.g. YouTube) — then
 * re-run: node scripts/generate-version-data.js
 */
window.VERSIONS = window.VERSIONS || {};
window.VERSIONS["v5-4"] = {
  id: "v5-4",
  label: "Version 5.4",
  note: "A full solid panel shifts coverage toward the dining terrace, opening the pool run to sky and a slimmer slat section.",
  thumb: "assets/aerial-overview.jpg",
  images: [
    { src: "assets/aerial-overview.jpg", caption: "Aerial Overview" },
    { src: "assets/courtyard-view.jpg", caption: "Courtyard View" },
    { src: "assets/dining-terrace.jpg", caption: "Dining Terrace" },
    { src: "assets/fireplace-detail.jpg", caption: "Fireplace Detail" },
    { src: "assets/interior-transition.jpg", caption: "Interior Transition" },
    { src: "assets/poolside-terrace.jpg", caption: "Poolside Terrace" }
  ],
  videos: [

  ]
};
