/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Edit versions/v5/meta.json for label/note, add/remove files in
 * versions/v5/assets/ for images and local videos, or add entries to
 * versions/v5/videos.json for non-file videos (e.g. YouTube) — then
 * re-run: node scripts/generate-version-data.js
 */
window.VERSIONS = window.VERSIONS || {};
window.VERSIONS["v5"] = {
  id: "v5",
  label: "Version 5",
  note: "Staggered pergola runs bridge the main house to a sculptural concrete fireplace tower, framing the pool in dappled light.",
  thumb: "assets/aerial-overview.jpg",
  images: [
    { src: "assets/aerial-overview.jpg", caption: "Aerial Overview" },
    { src: "assets/courtyard-view.jpg", caption: "Courtyard View" },
    { src: "assets/dining-terrace.jpg", caption: "Dining Terrace" },
    { src: "assets/evening-terrace.jpg", caption: "Evening Terrace" },
    { src: "assets/fireplace-detail.jpg", caption: "Fireplace Detail" },
    { src: "assets/fireplace-passage.jpg", caption: "Fireplace Passage" },
    { src: "assets/interior-transition.jpg", caption: "Interior Transition" },
    { src: "assets/poolside-terrace.jpg", caption: "Poolside Terrace" }
  ],
  videos: [

  ]
};
