/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Edit versions/v5/meta.json for label/note (and optionally this
 * version's own title-header hero video — heroPlaylistId/heroVideoIds/
 * heroVideoId, same shape as project-data.js's site-level hero), add/remove
 * files in versions/v5/assets/ for images and local videos, or add
 * entries to versions/v5/videos.json for non-file videos (e.g. YouTube) —
 * then re-run: node scripts/generate-version-data.js
 */
window.VERSIONS = window.VERSIONS || {};
window.VERSIONS["v5"] = {
  id: "v5",
  label: "Version 5",
  note: "Staggered pergola runs bridge the main house to a sculptural concrete fireplace tower, framing the pool in dappled light.",
  thumb: "assets/CLEARVIEW DECK-20260430-V5-01.jpg",
  // Title-header hero video — checked in this order, first non-empty wins,
  // falls back to the thumb image (above) as a static background if all
  // three are empty. See assets/js/common.js buildYouTubeHeroSrc().
  heroPlaylistId: "",
  heroVideoIds: [],
  heroVideoId: "",
  images: [
    { src: "assets/CLEARVIEW DECK-20260430-V5-01.jpg", caption: "CLEARVIEW DECK 20260430 V5 01" },
    { src: "assets/CLEARVIEW DECK-20260430-V5-02.jpg", caption: "CLEARVIEW DECK 20260430 V5 02" },
    { src: "assets/CLEARVIEW DECK-20260430-V5-03.jpg", caption: "CLEARVIEW DECK 20260430 V5 03" },
    { src: "assets/CLEARVIEW DECK-20260430-V5-04.jpg", caption: "CLEARVIEW DECK 20260430 V5 04" },
    { src: "assets/CLEARVIEW DECK-20260430-V5-05.jpg", caption: "CLEARVIEW DECK 20260430 V5 05" },
    { src: "assets/CLEARVIEW DECK-20260430-V5-05b.jpg", caption: "CLEARVIEW DECK 20260430 V5 05b" },
    { src: "assets/CLEARVIEW DECK-20260430-V5-06.jpg", caption: "CLEARVIEW DECK 20260430 V5 06" },
    { src: "assets/CLEARVIEW DECK-20260430-V5-07.jpg", caption: "CLEARVIEW DECK 20260430 V5 07" }
  ],
  videos: [

  ]
};
