/* AUTO-GENERATED by scripts/generate-reference-data.js — do not hand-edit.
 * Reflects whatever section folders currently exist under reference/
 * (excluding _template). Order is natural-sort by folder name, which is
 * also the display order on the Reference Images page. Re-run after
 * adding/removing a section folder: node scripts/generate-reference-data.js
 */
window.SECTION_IDS = [
  "TRELLIS"
];
