/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Edit versions/v5-5/meta.json for label/note, add/remove files in
 * versions/v5-5/assets/ for images and local videos, or add entries to
 * versions/v5-5/videos.json for non-file videos (e.g. YouTube) — then
 * re-run: node scripts/generate-version-data.js
 */
window.VERSIONS = window.VERSIONS || {};
window.VERSIONS["v5-5"] = {
  id: "v5-5",
  label: "Version 5.5",
  note: "A skylight cutout lets an existing tree grow through the roof plane, softening the structure above a row of loungers.",
  thumb: "assets/aerial-overview.jpg",
  images: [
    { src: "assets/aerial-overview.jpg", caption: "Aerial Overview" },
    { src: "assets/courtyard-view.jpg", caption: "Courtyard View" },
    { src: "assets/dining-terrace.jpg", caption: "Dining Terrace" },
    { src: "assets/fireplace-detail.jpg", caption: "Fireplace Detail" },
    { src: "assets/interior-transition.jpg", caption: "Interior Transition" },
    { src: "assets/poolside-terrace.jpg", caption: "Poolside Terrace" }
  ],
  videos: [

  ]
};
