/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Edit versions/dv5-5-1/meta.json for label/note (and optionally this
 * version's own title-header hero video — heroPlaylistId/heroVideoIds/
 * heroVideoId, same shape as project-data.js's site-level hero), add/remove
 * files in versions/dv5-5-1/assets/ for images and local videos, or add
 * entries to versions/dv5-5-1/videos.json for non-file videos (e.g. YouTube) —
 * then re-run: node scripts/generate-version-data.js
 */
window.VERSIONS = window.VERSIONS || {};
window.VERSIONS["dv5-5-1"] = {
  id: "dv5-5-1",
  label: "DV5.5-1 — Patio Deck",
  note: "Design-development drawing set for the pool deck: dimensioned plan, two building sections through the pergola bay, and a 3D massing study, developed from Concept Version 5.5.",
  thumb: "assets/axonometric-massing-view.jpg",
  // Title-header hero video — checked in this order, first non-empty wins,
  // falls back to the thumb image (above) as a static background if all
  // three are empty. See assets/js/common.js buildYouTubeHeroSrc().
  heroPlaylistId: "",
  heroVideoIds: [],
  heroVideoId: "",
  images: [
    { src: "assets/axonometric-massing-view.jpg", caption: "Axonometric Massing View" },
    { src: "assets/deck-and-pool-plan.jpg", caption: "Deck And Pool Plan" },
    { src: "assets/full-drawing-sheet.jpg", caption: "Full Drawing Sheet" },
    { src: "assets/section-1.jpg", caption: "Section 1" },
    { src: "assets/section-2.jpg", caption: "Section 2" }
  ],
  videos: [

  ]
};
