/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Edit versions/vX/meta.json for label/note, add/remove files in
 * versions/vX/assets/ for images and local videos, or add entries to
 * versions/vX/videos.json for non-file videos (e.g. YouTube) — then
 * re-run: node scripts/generate-version-data.js
 */
window.VERSIONS = window.VERSIONS || {};
window.VERSIONS["vX"] = {
  id: "vX",
  label: "Version Vx",
  note: "Desc",
  thumb: "assets/CLEARVIEW DECK-20260819-01-AI.jpg",
  images: [
    { src: "assets/CLEARVIEW DECK-20260819-01-AI.jpg", caption: "CLEARVIEW DECK 20260819 01 AI" },
    { src: "assets/CLEARVIEW DECK-20260819-04.2-IA.jpg", caption: "CLEARVIEW DECK 20260819 04.2 IA" },
    { src: "assets/CLEARVIEW DECK-20260819-04.3-AI-2.jpg", caption: "CLEARVIEW DECK 20260819 04.3 AI 2" },
    { src: "assets/CLEARVIEW DECK-20260819-04.3-AI.jpg", caption: "CLEARVIEW DECK 20260819 04.3 AI" },
    { src: "assets/CLEARVIEW DECK-20260819-07.2-AI.jpg", caption: "CLEARVIEW DECK 20260819 07.2 AI" },
    { src: "assets/CLEARVIEW DECK-20260819-08-AI.jpg", caption: "CLEARVIEW DECK 20260819 08 AI" },
    { src: "assets/CLEARVIEW DECK-20260819-09-AI.jpg", caption: "CLEARVIEW DECK 20260819 09 AI" },
    { src: "assets/CLEARVIEW DECK-20260819-10-AI.jpg", caption: "CLEARVIEW DECK 20260819 10 AI" },
    { src: "assets/CLEARVIEW DECK-20260819-12-AI-1.jpg", caption: "CLEARVIEW DECK 20260819 12 AI 1" },
    { src: "assets/CLEARVIEW DECK-20260819-12-AI-2.jpg", caption: "CLEARVIEW DECK 20260819 12 AI 2" },
    { src: "assets/CLEARVIEW DECK-20260819-13-AI.jpg", caption: "CLEARVIEW DECK 20260819 13 AI" },
    { src: "assets/CLEARVIEW DECK-20260819-14-AI-2.jpg", caption: "CLEARVIEW DECK 20260819 14 AI 2" },
    { src: "assets/CLEARVIEW DECK-20260819-14-AI.jpg", caption: "CLEARVIEW DECK 20260819 14 AI" },
    { src: "assets/CLEARVIEW DECK-20260819-15-AI.jpg", caption: "CLEARVIEW DECK 20260819 15 AI" },
    { src: "assets/CLEARVIEW DECK-20260819-17-AI.jpg", caption: "CLEARVIEW DECK 20260819 17 AI" },
    { src: "assets/CLEARVIEW DECK-20260819-18-AI.jpg", caption: "CLEARVIEW DECK 20260819 18 AI" }
  ],
  videos: [
    { type: "youtube", youtubeId: "as7UumMWGa0", caption: "Fire Pit" },
    { type: "youtube", youtubeId: "B7Y6PoER8PU", caption: "Sun Study" },
    { type: "youtube", youtubeId: "GIv6Fzz-06o", caption: "Projection Screen" },
    { type: "youtube", youtubeId: "J14n4W3_BQ4", caption: "Flythrough 1" },
    { type: "youtube", youtubeId: "xPEuINdMmh8", caption: "Flythrough 2" },
    { type: "youtube", youtubeId: "SzfP0PZthf8", caption: "Projection Screen 2" }
  ]
};
