/* AUTO-GENERATED by scripts/generate-reference-data.js — do not hand-edit.
 * Edit reference/TRELLIS/meta.json for title/note, add/remove files in
 * reference/TRELLIS/assets/ for images — then re-run:
 * node scripts/generate-reference-data.js
 */
window.SECTIONS = window.SECTIONS || {};
window.SECTIONS["TRELLIS"] = {
  id: "TRELLIS",
  title: "TRELLIS",
  note: "",
  images: [
    { src: "assets/2.jpg", caption: "2" },
    { src: "assets/3.jpg", caption: "3" },
    { src: "assets/4.jpg", caption: "4" },
    { src: "assets/16.jpg", caption: "16" },
    { src: "assets/1805moore-185.jpg", caption: "1805moore 185" },
    { src: "assets/vineyard2309-225.jpg", caption: "Vineyard2309 225" },
    { src: "assets/vineyard2309-256.jpg", caption: "Vineyard2309 256" }
  ]
};
