/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Edit versions/v5-2b/meta.json for label/note, add/remove files in
 * versions/v5-2b/assets/ for images and local videos, or add entries to
 * versions/v5-2b/videos.json for non-file videos (e.g. YouTube) — then
 * re-run: node scripts/generate-version-data.js
 */
window.VERSIONS = window.VERSIONS || {};
window.VERSIONS["v5-2b"] = {
  id: "v5-2b",
  label: "Version 5.2b",
  note: "The pergola extends further past the fireplace with a woven shade panel, adding a dedicated lounge run of chaises.",
  thumb: "assets/aerial-overview.jpg",
  images: [
    { src: "assets/aerial-overview.jpg", caption: "Aerial Overview" },
    { src: "assets/courtyard-view.jpg", caption: "Courtyard View" },
    { src: "assets/dining-terrace.jpg", caption: "Dining Terrace" },
    { src: "assets/fireplace-detail.jpg", caption: "Fireplace Detail" },
    { src: "assets/interior-transition.jpg", caption: "Interior Transition" },
    { src: "assets/poolside-terrace.jpg", caption: "Poolside Terrace" }
  ],
  videos: [

  ]
};
