/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Reflects whatever version folders currently exist under versions/
 * (excluding _template). Order is natural-sort by folder name, which is
 * also the display order everywhere. Re-run after adding/removing a
 * version folder: node scripts/generate-version-data.js
 */
window.VERSION_IDS = [
  "V5.5",
  "V5.6"
];
