/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Reflects whatever version folders currently exist under versions/
 * (excluding _template). Order is natural-sort by folder name, which is
 * also the display order everywhere. Re-run after adding/removing a
 * version folder: node scripts/generate-version-data.js
 */
window.VERSION_IDS = [
  "v5",
  "v5-2",
  "v5-2b",
  "v5-3",
  "v5-4",
  "v5-5",
  "v5-6",
  "vX"
];
