/* AUTO-GENERATED by scripts/generate-version-data.js — do not hand-edit.
 * Edit versions/V5.6/meta.json for label/note (and optionally this
 * version's own title-header hero video — heroPlaylistId/heroVideoIds/
 * heroVideoId, same shape as project-data.js's site-level hero), add/remove
 * files in versions/V5.6/assets/ for images and local videos, or add
 * entries to versions/V5.6/videos.json for non-file videos (e.g. YouTube) —
 * then re-run: node scripts/generate-version-data.js
 */
window.VERSIONS = window.VERSIONS || {};
window.VERSIONS["V5.6"] = {
  id: "V5.6",
  label: "V5.6",
  note: "BUILT IN CHACE LOUNGE AREA, SLIDING TRELLIS ROOF, SLIDING PANELS AND PROJECTOR SCREEN",
  thumb: "assets/2026-08-21 13-23-24 - Custom.jpg",
  // Title-header hero video — checked in this order, first non-empty wins,
  // falls back to the thumb image (above) as a static background if all
  // three are empty. See assets/js/common.js buildYouTubeHeroSrc().
  heroPlaylistId: "PLL5c6ekNKKMA",
  heroVideoIds: [],
  heroVideoId: "",
  images: [
    { src: "assets/2026-08-21 13-23-24 - Custom.jpg", caption: "2026 08 21 13 23 24 Custom" },
    { src: "assets/2026-08-21 13-25-16 - Custom.jpg", caption: "2026 08 21 13 25 16 Custom" },
    { src: "assets/2026-08-21 13-25-39 - Custom.jpg", caption: "2026 08 21 13 25 39 Custom" },
    { src: "assets/2026-08-21 13-26-34 - Custom.jpg", caption: "2026 08 21 13 26 34 Custom" },
    { src: "assets/2026-08-21 13-27-33 - Custom.jpg", caption: "2026 08 21 13 27 33 Custom" },
    { src: "assets/2026-08-21 13-28-10 - Custom.jpg", caption: "2026 08 21 13 28 10 Custom" },
    { src: "assets/2026-08-21 13-28-41 - Custom.jpg", caption: "2026 08 21 13 28 41 Custom" },
    { src: "assets/2026-08-21 13-39-44 - Custom.jpg", caption: "2026 08 21 13 39 44 Custom" },
    { src: "assets/2026-08-21 13-40-48 - Custom.jpg", caption: "2026 08 21 13 40 48 Custom" },
    { src: "assets/2026-08-21 13-41-23 - Custom.jpg", caption: "2026 08 21 13 41 23 Custom" },
    { src: "assets/2026-08-21 13-44-06 - Custom.jpg", caption: "2026 08 21 13 44 06 Custom" }
  ],
  videos: [
    { type: "youtube", youtubeId: "99A_l5_iOCQ", caption: "2" },
    { type: "youtube", youtubeId: "k20NqEPjJjg", caption: "3" },
    { type: "youtube", youtubeId: "ydqCJixp04g", caption: "4" },
    { type: "youtube", youtubeId: "QDXPZD37WJE", caption: "5" },
    { type: "youtube", youtubeId: "iUkeonKT4n0", caption: "6" },
    { type: "youtube", youtubeId: "kSH-iOcrQ1E", caption: "7" },
    { type: "youtube", youtubeId: "kpLIvgicTyA", caption: "1" }
  ]
};
